--- isle-apache/Dockerfile	2021-04-06 15:50:45.000000000 -0400
+++ Dockerfile	2021-04-06 15:51:56.000000000 -0400
@@ -1,5 +1,5 @@
 # @see https://github.com/AdoptOpenJDK/openjdk-docker/blob/master/8/jdk/ubuntu/Dockerfile.hotspot.releases.full
-FROM adoptopenjdk:8-jdk-hotspot
+FROM 840783682283.dkr.ecr.us-east-1.amazonaws.com/adoptopenjdk/adoptopenjdk:8-jdk-hotspot
 
 ENV INITRD=no \
     ISLANDORA_UID=${ISLANDORA_UID:-1000} \
